table 'Page Visuals'
	lineageTag: 22f470c9-88c3-48c4-bf59-3477192f5c8a

	column PageID
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 9d2423e2-dcb1-40e4-bb4c-71a03b1f058a
		summarizeBy: none
		sourceColumn: PageID

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VisualID
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: abb0198f-1a9c-4d57-8ec2-867a94c8745b
		summarizeBy: none
		sourceColumn: VisualID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Visual Type'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 4b91a94f-ee73-4f5b-aa53-2d92675c803d
		summarizeBy: none
		sourceColumn: Visual Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'AltText Type'
		dataType: string
		isAvailableInMdx: false
		lineageTag: d066ee2a-cb6b-4f7b-a7fe-f54420719040
		summarizeBy: none
		sourceColumn: AltText Type

		annotation SummarizationSetBy = Automatic

	column 'AltText Value'
		dataType: string
		isAvailableInMdx: false
		lineageTag: a51256f2-c219-4424-a796-eda4947b0acf
		summarizeBy: none
		sourceColumn: AltText Value

		annotation SummarizationSetBy = Automatic

	column 'Tab Order'
		dataType: string
		lineageTag: d8fcc64d-4f58-4901-a796-bfc364c0610c
		summarizeBy: none
		sourceColumn: Tab Order
		sortByColumn: 'Tab Order Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Tab Order Sort'
		dataType: string
		isHidden
		lineageTag: 5e12a645-a00d-450a-83fc-8b388444ea2c
		summarizeBy: none
		sourceColumn: Tab Order Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Actual X'
		dataType: decimal
		isAvailableInMdx: false
		lineageTag: 01de2ff2-43b1-4c53-80e5-e0c4e96fbf3a
		summarizeBy: none
		sourceColumn: Actual X

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Y'
		dataType: decimal
		isAvailableInMdx: false
		lineageTag: b78f80b2-da47-4fac-828e-479d75b28e3c
		summarizeBy: none
		sourceColumn: Actual Y

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Layer Order'
		dataType: string
		isAvailableInMdx: false
		lineageTag: bd0c3c33-c4bd-47da-ba06-c3a7f04e4195
		summarizeBy: none
		sourceColumn: Layer Order

		annotation SummarizationSetBy = Automatic

	column 'Title Text Value'
		dataType: string
		isAvailableInMdx: false
		lineageTag: 0787c32e-0d50-48d2-a20f-3eec03ef43ac
		summarizeBy: none
		sourceColumn: Title Text Value

		annotation SummarizationSetBy = Automatic

	column Width
		dataType: decimal
		isAvailableInMdx: false
		lineageTag: 722b2d50-5636-452b-a6a0-a0214ebb8ef6
		summarizeBy: none
		sourceColumn: Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Height
		dataType: decimal
		isAvailableInMdx: false
		lineageTag: 3c943fe9-887c-4e97-84aa-54ff1eb8c360
		summarizeBy: none
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Page Visuals-67fd3af8-298c-4c6e-bf86-b58e5cf6cd4a' = m
		mode: import
		queryGroup: 'Page Visuals'
		source =
				// Load the initial data from the 'Page Visuals Starter' table
				let
					#"Loaded Page Visuals Starter" = #"Page Visuals Starter",
				
				// Rename the 'singleVisual.visualType' column to 'Visual Type'
					#"Rename Visual Type" = Table.RenameColumns(#"Loaded Page Visuals Starter", {{"singleVisual.visualType", "Visual Type"}}),
				
				// Expand the 'singleVisualGroup' column to include 'displayName' and 'groupMode'
					#"Expanded Single Visual Group" = Table.ExpandRecordColumn(#"Rename Visual Type", "singleVisualGroup", {"displayName", "groupMode"}, {"Visual Group Name", "Visual Group Type"}),
				
				// Replace null values in 'Visual Type' with 'visual group' if 'Visual Group Name' is not null
					#"Replaced Visual Type Values" = Table.ReplaceValue(#"Expanded Single Visual Group", each [Visual Type], each if ([Visual Type] = null and [Visual Group Name] <> null) then "visual group" else [Visual Type], Replacer.ReplaceValue, {"Visual Type"}),
				
				// Change the data type of the 'Visual Type' column to text
					#"Changed Visual Type Column Type" = Table.TransformColumnTypes(#"Replaced Visual Type Values", {{"Visual Type", type text}}),
				
				// Merge with 'Page Visual Actual Coordinates' table based on 'PageIDname'
					#"Merged with Actual Coordinates" = Table.NestedJoin(#"Changed Visual Type Column Type", {"PageIDname"}, #"Page Visual Actual Coordinates", {"PageIDname"}, "Page Visual Actual Coordinates", JoinKind.LeftOuter),
				
				// Expand the merged 'Page Visual Actual Coordinates' table to include specific fields
					#"Expanded Actual Coordinates" = Table.ExpandTableColumn(#"Merged with Actual Coordinates", "Page Visual Actual Coordinates", {"tabOrder", "x", "y", "z"}, {"actual tabOrder", "actual x", "actual y", "Layer Order"}),
				
				// Merge with 'Page Visual Tab Order' table based on 'PageIDname'
					#"Merged with Tab Order" = Table.NestedJoin(#"Expanded Actual Coordinates", {"PageIDname"}, #"Page Visual Tab Order", {"PageIDname"}, "Page Visual Tab Order", JoinKind.LeftOuter),
				
				// Expand the merged 'Page Visual Tab Order' table to include specific fields
					#"Expanded Tab Order" = Table.ExpandTableColumn(#"Merged with Tab Order", "Page Visual Tab Order", {"Tab Order", "Tab Order 1", "Tab Order 2", "Tab Order 3", "Tab Order 4", "Tab Order 5", "Tab Order Sort"}, {"Tab Order", "Tab Order 1", "Tab Order 2", "Tab Order 3", "Tab Order 4", "Tab Order 5", "Tab Order Sort"}),
				
				// Select specific columns from the expanded table
					#"Selected Relevant Columns" = Table.SelectColumns(#"Expanded Tab Order", {"Report Key", "PageID", "Page Name", "VisualID", "pageWidth", "pageHeight", "x", "y", "z", "width", "height", "tabOrder", "name", "parentName", "Visual Type", "Visual Group Name", "layouts.position.tabOrder", "actual tabOrder", "actual x", "actual y", "Layer Order", "Tab Order", "Tab Order 1", "Tab Order 2", "Tab Order 3", "Tab Order 4", "Tab Order 5", "Tab Order Sort"}),
				
				// Merge with 'Page Visuals Alt Text' table based on 'VisualID'
					#"Merged with Alt Text" = Table.NestedJoin(#"Selected Relevant Columns", {"VisualID"}, #"Page Visuals Alt Text", {"VisualID"}, "Page Visuals Alt Text", JoinKind.LeftOuter),
				
				// Expand the merged 'Page Visuals Alt Text' table to include 'AltText Type' and 'AltText Value'
					#"Expanded Alt Text" = Table.ExpandTableColumn(#"Merged with Alt Text", "Page Visuals Alt Text", {"AltText Type", "AltText Value"}, {"AltText Type", "AltText Value"}),
				
				// Merge with 'Page Visual Titles' table based on 'VisualID'
					#"Merged with Visual Titles" = Table.NestedJoin(#"Expanded Alt Text", {"VisualID"}, #"Page Visual Titles", {"VisualID"}, "Page Visual Titles", JoinKind.LeftOuter),
				
				// Expand the merged 'Page Visual Titles' table to include specific fields
					#"Expanded Visual Titles" = Table.ExpandTableColumn(#"Merged with Visual Titles", "Page Visual Titles", {"Title Show Type", "Title Show Value", "Title Text Type", "Title Text Value"}, {"Title Show Type", "Title Show Value", "Title Text Type", "Title Text Value"}),
				
				// Sort rows by 'actual tabOrder' in descending order
					#"Sorted Rows" = Table.Sort(#"Expanded Visual Titles", {{"actual tabOrder", Order.Descending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"actual tabOrder", "Actual Tab Order"}, {"actual x", "Actual X"}, {"actual y", "Actual Y"}, {"height", "Height"}, {"layouts.position.tabOrder", "Layout Position Tab Order"}, {"name", "Name"}, {"pageHeight", "Page Height"}, {"pageWidth", "Page Width"}, {"parentName", "Parent Name"}, {"width", "Width"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"PageID", "VisualID", "Width", "Height", "Visual Type", "Actual X", "Actual Y", "Layer Order", "Tab Order", "Tab Order Sort", "AltText Type", "AltText Value", "Title Text Value"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Width", Currency.Type},{"Height", Currency.Type},{"Actual X", Currency.Type},{"Actual Y", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":25,"keyColumnNames":[],"queryRelationships":[{"keyColumnCount":1,"keyColumn":21,"otherKeyColumnIdentity":"Section1/Page Visual actual coordinates/Changed Type3.{PageIDname,0}","KeyColumnCount":1}],"columnIdentities":["Section1/Page Visuals/Replaced Value1.{PageID,0}","Section1/Page Visuals/Replaced Value1.{Page Name,1}","Section1/Page Visuals/Replaced Value1.{VisualID,2}","Section1/Page Visuals/Replaced Value1.{pageHeight,3}","Section1/Page Visuals/Replaced Value1.{pageWidth,4}","Section1/Page Visuals/Replaced Value1.{x,5}","Section1/Page Visuals/Replaced Value1.{y,6}","Section1/Page Visuals/Replaced Value1.{z,7}","Section1/Page Visuals/Replaced Value1.{width,8}","Section1/Page Visuals/Replaced Value1.{height,9}","Section1/Page Visuals/Replaced Value1.{config,10}","Section1/Page Visuals/Replaced Value1.{filters,11}","Section1/Page Visuals/Replaced Value1.{tabOrder,12}","Section1/Page Visuals/Replaced Value1.{query,13}","Section1/Page Visuals/Replaced Value1.{dataTransforms,14}","Section1/Page Visuals/Replaced Value1.{name,15}","Section1/Page Visuals/Replaced Value1.{parentName,16}","Section1/Page Visuals/Changed Type4.{Visual Type,17}","Section1/Page Visuals/Replaced Value1.{Selection Pane Name,18}","Section1/Page Visuals/Replaced Value1.{Visual Group Name,19}","Section1/Page Visuals/Replaced Value1.{Visual Group Type,20}","Section1/Page Visuals/Replaced Value1.{PageIDname,21}","Section1/Page Visuals/Replaced Value1.{PageIDparentName,22}","Section1/Page Visual actual coordinates/Grouped Rows1.{x,3}","Section1/Page Visual actual coordinates/Grouped Rows1.{y,4}"],"ColumnCount":25,"KeyColumnNames":[],"ColumnIdentities":["Section1/Page Visuals/Replaced Value1.{PageID,0}","Section1/Page Visuals/Replaced Value1.{Page Name,1}","Section1/Page Visuals/Replaced Value1.{VisualID,2}","Section1/Page Visuals/Replaced Value1.{pageHeight,3}","Section1/Page Visuals/Replaced Value1.{pageWidth,4}","Section1/Page Visuals/Replaced Value1.{x,5}","Section1/Page Visuals/Replaced Value1.{y,6}","Section1/Page Visuals/Replaced Value1.{z,7}","Section1/Page Visuals/Replaced Value1.{width,8}","Section1/Page Visuals/Replaced Value1.{height,9}","Section1/Page Visuals/Replaced Value1.{config,10}","Section1/Page Visuals/Replaced Value1.{filters,11}","Section1/Page Visuals/Replaced Value1.{tabOrder,12}","Section1/Page Visuals/Replaced Value1.{query,13}","Section1/Page Visuals/Replaced Value1.{dataTransforms,14}","Section1/Page Visuals/Replaced Value1.{name,15}","Section1/Page Visuals/Replaced Value1.{parentName,16}","Section1/Page Visuals/Changed Type4.{Visual Type,17}","Section1/Page Visuals/Replaced Value1.{Selection Pane Name,18}","Section1/Page Visuals/Replaced Value1.{Visual Group Name,19}","Section1/Page Visuals/Replaced Value1.{Visual Group Type,20}","Section1/Page Visuals/Replaced Value1.{PageIDname,21}","Section1/Page Visuals/Replaced Value1.{PageIDparentName,22}","Section1/Page Visual actual coordinates/Grouped Rows1.{x,3}","Section1/Page Visual actual coordinates/Grouped Rows1.{y,4}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":21,"otherKeyColumnIdentity":"Section1/Page Visual actual coordinates/Changed Type3.{PageIDname,0}","KeyColumnCount":1}]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

